config/routes.rb
Rails.application.routes.draw do
  resources :books
  root 'books#index'

  resources :searches
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  def self.search(search)
    if search
      where(["name LIKE?", "%#{search}%"])
    else
      all
    end
  end
end

app/models/search.rb
class Search < ApplicationRecord
  def search_books
    books = Book.all

    books = books.where(["name LIKE ?", "%#{keywords}%"]) if keywords.present?
    books = books.where(["category LIKE ?", category]) if category.present?
    books = books.where(["price >= ?", min_price]) if min_price.present?
    books = books.where(["price <= ?", max_price]) if max_price.present?
    books = books.where(["isbn LIKE ?", isbn]) if isbn.present?

    return books
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.search(params[:search])
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:name, :category, :price, :isbn)
    end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def new
    @search = Search.new
    @categories = Book.uniq.pluck(:category)
  end

  def create
    @search = Search.create(search_params)
    redirect_to @search
  end

  def show
    @search = Search.find(params[:id])
  end

  private
  def search_params
    params.require(:search).permit(:keywords, :category, :min_price, :max_price, :isdn)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/books/_form.html.erb
<%= form_for(book) do |f| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :category %>
    <%= f.text_field :category %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="field">
    <%= f.label :isbn %>
    <%= f.number_field :isbn %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>
<%= form_tag books_path, method: 'get' do %>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag "search" %>
<% end  %>

<%= link_to "Advanced search", new_search_path %>


<h1>Books</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Category</th>
      <th>Price</th>
      <th>Isbn</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.name %></td>
        <td><%= book.category %></td>
        <td><%= book.price %></td>
        <td><%= book.isbn %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @book.name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @book.category %>
</p>

<p>
  <strong>Price:</strong>
  <%= @book.price %>
</p>

<p>
  <strong>Isbn:</strong>
  <%= @book.isbn %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookstore</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/searches/new.html.erb
<h1>Advanced Search</h1>

<%= simple_form_for @search do |s| %>
  <%= s.input :keywords %>
  <%= s.label :category %>
  <%= s.select :category, options_for_select(@categories), include_blank: true %>
  <%= s.input :min_price %>
  <%= s.input :max_price %>
  <%= s.input :isbn %>
  <%= s.button :submit %>
<% end %>

app/views/searches/show.html.erb
<h1>Search Result</h1>

<p><%= link_to 'Back', new_search_path %></p>

<% if @search.search_books.empty? %>
<p>No Records Found</p>

<% else %>
  <% @search.search_books.each do |b| %>
    <div class="div">
      <h1><%= b.name %></h1>
      <p>Price: $<%= b.price %></p>
      <p>category: <%= b.category %></p>
      <p>ISBN: <%= b.isbn %></p>
    </div>
  <% end %>
<% end %>